version: '3'
services:
   api:
     image: wiroforce-api
     restart: always
     environment:
       - JWT_SECRET=12345678 
       - APP_PORT=9013
       - DB_HOST=db
       - DB_PORT=3306
       - DB_USERNAME=root
       - DB_PASSWORD=8*9klMy6!Lp023
       - DB_NAME=wiroforce
       - MINIO_URL=conwiro.nat.cu
       - MINIO_PORT=9010
       - MINIO_ACCESS_KEY=admin775
       - MINIO_SECRET_KEY=Jo8Pm*gh
       - DEFAULT_BUCKET=wiro-force
     build:
          context: .
     ports:
       - 9013:3000
     depends_on: 
       - db
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=8*9klMy6!Lp023
       - MYSQL_DATABASE=wiroforce
     ports:
       - 9015:3306
volumes:
  db_data: {}