version: '3'
services:
   api:
     image: wiroforce-api
     restart: always
     environment:
       - JWT_SECRET=5412e42ad84cba4784c4f1be611515311605f9c2 
       - APP_PORT=3000
       - DB_HOST=db
       - DB_PORT=3306
       - DB_USER=root
       - DB_PASSWORD=xxxxx
       - DB_NAME=wiroforce
       - MINIO_HOST_URL=minio
       - MINIO_HOST_PORT=9000
       - MINIO_URL=xxxx
       - MINIO_PORT=xxxx
       - MINIO_ACCESS_KEY=xxxxx
       - MINIO_SECRET_KEY=xxxxx
       - DEFAULT_BUCKET=wiroforce-storage
       - SECRET_BUCKET=wiro-force-secret
       - MAIL_SERVICE=gmail
       - MAIL_USER=xxxxx
       - MAIL_PASSWORD=xxxxx
       - MAIL_FROM=xxxxx
       - RABBITMQ_USER=xxxx
       - RABBITMQ_PASSWORD=xxxxx
       - RABBITMQ_HOST=rabbitmq:5672/wiroforce
       - RABBITMQ_QUEUE_NAME=wiroforce_payments
     build:
          context: .
     ports:
       - 9013:3000
     depends_on: 
       - db
       - minio

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=xxxxxx
       - MYSQL_DATABASE=wiroforce
     ports:
       - 9015:3306

   minio:
     image: minio/minio:latest
     restart: always
     volumes:
      - wiroforce-storage:/data
     command: minio server /data
     ports:
       - 9016:9000
     environment:
       MINIO_ROOT_USER: admin775
       MINIO_ROOT_PASSWORD: Jo8Pm*gh

   metabase:
    image: metabase/metabase:v0.39.2
    restart: always
    ports:
      - 9012:3000
    environment: 
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data

volumes:
  db_data:
  wiroforce-storage:
  metabase-data:

networks: 
  default: 
    external: 
      name: wiroforce    